apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello81
spec:
  hosts:
  - '*'
  gateways:
    - gateway
  http:
    - route:
      - destination:
          host: hello-service-demonginx.demonginx.svc.cluster.local
          port:
            number: 88
