apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.Namespace }}
  namespace: {{ $.Values.Namespace }}
spec:
  type: NodePort
  ports:
    - port: 88
      targetPort: 80
  selector:
    app: {{ $.Values.app }}