apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $.Values.hpaName }}
  namespace: {{ $.Values.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $.Values.deploymentName }}
  minReplicas: {{ $.Values.hpaMinReplicas }}
  maxReplicas: {{ $.Values.hpamaxReplicas }}
  targetCPUUtilizationPercentage: 10