apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ $.Values.pdbName }}
  namespace: {{ $.Values.Namespace }}
spec:
  minAvailable: 1  #maxUnavailable: 25%
  selector:
    matchLabels:
      app: {{ $.Values.app }}